f01     0       512     10      1
f02     0       8192    10      1
f03     0       512     5       1       512     .000001
;       start   dur     amp     pitch   rise    decay   leftfac rightfac
i01     0       6       15000   131     1       1       1       0
i01     1       4       15000   196     1       1       0       1
i01     2       3       15000   165     1       1       .5      .5
i01     3       3       15000   262     1       1       0       1
e
